ALTER TYPE "NotificationType" ADD VALUE 'JOIN_REQUEST_SUBMITTED';
ALTER TYPE "NotificationType" ADD VALUE 'JOIN_REQUEST_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE 'JOIN_REQUEST_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE 'NEW_MESSAGE';
ALTER TYPE "NotificationType" ADD VALUE 'STALE_PENDING';
